openapi: 3.0.1
info:
  title: launtel
  version: 0.0.1

security:
  - AuthHeader: []

servers:
  - url: "https://launtel.vercel.app"

components:
  securitySchemes:
    AuthHeader:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths: {}
